In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
#
# https://www.dataquest.io/blog/jupyter-notebook-tutorial/
#
from __future__ import print_function
import torch

In [2]:
torch.__version__

'2.4.0+cu121'

In [73]:
!ifconfig |grep broadcast

        inet 129.254.23.123  netmask 255.255.255.0  broadcast 129.254.23.255


In [74]:
!conda env list

# conda environments:
#
Pruning                  /home/std/.conda/envs/Pruning
a1003                 *  /home/std/.conda/envs/a1003
tf                       /home/std/.conda/envs/tf
whisper                  /home/std/.conda/envs/whisper
yolo                     /home/std/.conda/envs/yolo
base                     /home/std/miniforge3
DeepKNLP-24.03           /home/std/miniforge3/envs/DeepKNLP-24.03



In [75]:
!which jupyter

/home/std/.conda/envs/a1003/bin/jupyter


In [76]:
!which python

/home/std/.conda/envs/a1003/bin/python


In [4]:
!nvidia-smi

Mon Nov 25 16:09:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:65:00.0  On |                  N/A |
| 18%   34C    P8              21W / 250W |    617MiB / 11264MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
!pwd

/home/std/test


In [6]:
torch.cuda.is_available()

True

In [7]:
#List all the files in the current directory
!ls -lh

합계 332K
-rw-rw-r-- 1 std std 207K 11월 25 15:57 '2024년도 B1004 PyTorch 기반 딥러닝 기초 (4차).pdf'
-rw-rw-r-- 1 std std  17K 11월 25 16:08  Pytorch_tutorial.ipynb
-rw-rw-r-- 1 std std  98K 11월 25 16:08  tensor_tutorial.ipynb
-rw-rw-r-- 1 std std  867 11월 25 16:05  test_pytorch.txt


What about all `*Tensor`s?
Press <esc> to get out of help

In [8]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [83]:
torch.cuda.*?

torch.cuda.Any
torch.cuda.BFloat16Storage
torch.cuda.BFloat16Tensor
torch.cuda.BoolStorage
torch.cuda.BoolTensor
torch.cuda.ByteStorage
torch.cuda.ByteTensor
torch.cuda.CUDAGraph
torch.cuda.CUDAPluggableAllocator
torch.cuda.Callable
torch.cuda.CharStorage
torch.cuda.CharTensor
torch.cuda.ComplexDoubleStorage
torch.cuda.ComplexFloatStorage
torch.cuda.CudaError
torch.cuda.DeferredCudaCallError
torch.cuda.Device
torch.cuda.DoubleStorage
torch.cuda.DoubleTensor
torch.cuda.Event
torch.cuda.ExternalStream
torch.cuda.FloatStorage
torch.cuda.FloatTensor
torch.cuda.HalfStorage
torch.cuda.HalfTensor
torch.cuda.IntStorage
torch.cuda.IntTensor
torch.cuda.List
torch.cuda.LongStorage
torch.cuda.LongTensor
torch.cuda.Optional
torch.cuda.OutOfMemoryError
torch.cuda.ShortStorage
torch.cuda.ShortTensor
torch.cuda.Stream
torch.cuda.StreamContext
torch.cuda.Tuple
torch.cuda.Union
torch.cuda.__all__
torch.cuda.__annotations__
torch.cuda.__builtins__
torch.cuda.__cached__
torch.cuda.__class__
torch.cuda.__d

In [84]:
torch.cuda.is_available?

Signature: torch.cuda.is_available() -> bool
Docstring: Return a bool indicating if CUDA is currently available.
File:      ~/.conda/envs/a1003/lib/python3.10/site-packages/torch/cuda/__init__.py
Type:      function

In [3]:
torch.nn.Module

torch.nn.modules.module.Module

In [4]:
#
# ? (after a function, method or object) shows documentation string
#
torch.nn.Module?

Init signature: torch.nn.Module(*args, **kwargs) -> None
Docstring:     
Base class for all neural network modules.

Your models should also subclass this class.

Modules can also contain other Modules, allowing to nest them in
a tree structure. You can assign the submodules as regular attributes::

    import torch.nn as nn
    import torch.nn.functional as F

    class Model(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv1 = nn.Conv2d(1, 20, 5)
            self.conv2 = nn.Conv2d(20, 20, 5)

        def forward(self, x):
            x = F.relu(self.conv1(x))
            return F.relu(self.conv2(x))

Submodules assigned in this way will be registered, and will have their
parameters converted too when you call :meth:`to`, etc.

.. note::
    As per the example above, an ``__init__()`` call to the parent class
    must be made before assignment on the child.

:ivar training: Boolean represents whether this module is in training or
            

In [6]:
torch?

Type:        module
String form: <module 'torch' from '/home/std/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py'>
File:        ~/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py
Docstring:  
The torch package contains data structures for multi-dimensional
tensors and defines mathematical operations over these tensors.
Additionally, it provides many utilities for efficient serialization of
Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations
on an NVIDIA GPU with compute capability >= 3.0.

In [5]:
#
# ?? (after a function, method or object) shows source code
#
torch.nn.Module??

Init signature: torch.nn.Module(*args, **kwargs) -> None
Source:        
class Module:
    r"""Base class for all neural network modules.

    Your models should also subclass this class.

    Modules can also contain other Modules, allowing to nest them in
    a tree structure. You can assign the submodules as regular attributes::

        import torch.nn as nn
        import torch.nn.functional as F

        class Model(nn.Module):
            def __init__(self):
                super().__init__()
                self.conv1 = nn.Conv2d(1, 20, 5)
                self.conv2 = nn.Conv2d(20, 20, 5)

            def forward(self, x):
                x = F.relu(self.conv1(x))
                return F.relu(self.conv2(x))

    Submodules assigned in this way will be registered, and will have their
    parameters converted too when you call :meth:`to`, etc.

    .. note::
        As per the example above, an ``__init__()`` call to the parent class
        must be made before assignment on the

In [7]:
torch??

Type:        module
String form: <module 'torch' from '/home/std/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py'>
File:        ~/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py
Source:     
# mypy: allow-untyped-defs

r"""
The torch package contains data structures for multi-dimensional
tensors and defines mathematical operations over these tensors.
Additionally, it provides many utilities for efficient serialization of
Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations
on an NVIDIA GPU with compute capability >= 3.0.
"""

import math
import os
import sys
import platform
import textwrap
import ctypes
import inspect
import threading
import pdb
import importlib
import importlib.util

# multipy/deploy is setting this import before importing torch, this is the most
# reliable way we have to detect if we're running within deploy.
# https://github.com/pytorch/multipy/blob/d60

#Vectors (1D Tensors)

`torch.tensor` infers the dtype automatically, while `torch.Tensor` returns a torch.FloatTensor. \\
I would recommend to stick to torch.tensor, which also has arguments like dtype, if you would like to change the type.

In [10]:
[1, 2, 3, 4] # 1x4
[[1,2,3,4], [5,6,7,8]] # 2x4

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
# Creates a 1D tensor of integers 1 to 4
v = torch.tensor([1,2,3,4])
v

tensor([1, 2, 3, 4])

In [9]:
torch.*tensor?

torch.as_tensor
torch.is_tensor
torch.quantize_per_tensor
torch.scalar_tensor
torch.sparse_bsc_tensor
torch.sparse_bsr_tensor
torch.sparse_compressed_tensor
torch.sparse_coo_tensor
torch.sparse_csc_tensor
torch.sparse_csr_tensor
torch.tensor

In [10]:
torch.tensor?

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the de

In [11]:
torch.tensor??

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the de

In [13]:
v.shape

torch.Size([4])

In [14]:
v.shape?

Type:            Size
String form:     torch.Size([4])
Length:          1
File:            ~/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py
Docstring:       <no docstring>
Class docstring:
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [13]:
v[-1]

tensor(4)

In [15]:
v = torch.tensor([1, 2, 3, 4])
print(v)

tensor([1, 2, 3, 4])


In [18]:
dir(v)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed_

In [21]:
v.T?


Type:        Tensor
String form: tensor([1, 2, 3, 4])
Length:      4
File:        ~/.conda/envs/a1003/lib/python3.10/site-packages/torch/__init__.py
Docstring:   <no docstring>

In [15]:
v.dtype

torch.int64

In [16]:
v.shape

torch.Size([4])

In [17]:
v.size()

torch.Size([4])

In [18]:
x = torch.rand(3,4)
print(x)

tensor([[0.3141, 0.2123, 0.2350, 0.3254],
        [0.7191, 0.4207, 0.2525, 0.3114],
        [0.0291, 0.2097, 0.3938, 0.9882]])


In [19]:
x.shape

torch.Size([3, 4])

In [20]:
x.size()

torch.Size([3, 4])

In [21]:
x.size(0)

3

In [22]:
x.size(1)

4

In [23]:
#Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [24]:
w = torch.tensor([1,0,2,0])
w

tensor([1, 0, 2, 0])

In [25]:
# Element-wise multiplication
v * w

tensor([1, 0, 6, 0])

In [26]:
# inner product : 1*1 + 2*0 + 3*2 + 4*0
torch.dot(v, w)

tensor(7)

torch.tensor vs. torch.Tensor (refer to [link](https://discuss.pytorch.org/t/difference-between-torch-tensor-and-torch-tensor/106816/4))  
"*torch.Tensor(10) will return an uninitialized FloatTensor with 10 **values**, while torch.tensor(10) will return a LongTensor containing a **single value**(10).*"

In [22]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
print(x)

tensor([6., 0., 1., 6., 4.])


In [25]:
T=torch.Tensor(5)
print(T)

tensor([-3.7014e+16,  3.0726e-41, -3.3142e+16,  3.0726e-41,  1.1210e-43])


In [27]:
T.random_?

Docstring:
random_(from=0, to=None, *, generator=None) -> Tensor

Fills :attr:`self` tensor with numbers sampled from the discrete uniform
distribution over ``[from, to - 1]``. If not specified, the values are usually
only bounded by :attr:`self` tensor's data type. However, for floating point
types, if unspecified, range will be ``[0, 2^mantissa]`` to ensure that every
value is representable. For example, `torch.tensor(1, dtype=torch.double).random_()`
will be uniform in ``[0, 2^53]``.
Type:      builtin_function_or_method

In [28]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 7.0, last: 7.0


In [29]:
# Extract sub-Tensor [from:to) : Slicing
x[1 : 2]

tensor([6.])

In [30]:
 x[1 : 2 + 1]

tensor([6., 7.])

In [31]:
x[2:5]

tensor([7., 5., 7.])

In [32]:
x[:4]

tensor([7., 6., 7., 5.])

In [33]:
x[:]

tensor([7., 6., 7., 5., 7.])

In [34]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
# Note that torch.range is deprecated in favor of torch.arange().
v = torch.arange(1, 4 + 1)
v

tensor([1, 2, 3, 4])

In [35]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([ 1,  4,  9, 16]) tensor([1, 2, 3, 4])


# Matrices (2D Tensors)

In [36]:
# Square all elements in the tensor
m = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
m

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [37]:
m.dim()

2

In [38]:
m.size()

torch.Size([2, 4])

In [39]:
m.shape

torch.Size([2, 4])

In [40]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [41]:
# Return the total number of elements, hence num-el (number of elements)
m.numel()

8

In [42]:
#Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3)

In [43]:
#Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3)

In [44]:
m[:, 0]

tensor([1, 5])

In [45]:
#Indexing column 1, all rows (returns size 2)
print(m[:, 1], m[:,1].shape, sep=' , ')

tensor([2, 6]) , torch.Size([2])


In [46]:
#Indexing column 1, all rows (returns size 2x1)
print(m[:, [1]], m[:, [1]].shape, sep=' , ')

tensor([[2],
        [6]]) , torch.Size([2, 1])


In [47]:
#Indexing row 0, all column (returns size 4)
print(m[0, :], m[0, :].shape, sep=' , ')

tensor([1, 2, 3, 4]) , torch.Size([4])


In [48]:
#Indexing row 0, all column (returns size 1x4)
print(m[[0], :], m[[0], :].shape, sep=' , ') 

tensor([[1, 2, 3, 4]]) , torch.Size([1, 4])


In [49]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[1.0804, 2.1276, 3.9289, 4.4160],
        [5.1268, 6.6648, 7.5733, 8.8255]])

In [50]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[0.8740, 1.1633, 2.9295, 3.0395],
        [4.6902, 5.7230, 6.3443, 7.2010]])

In [51]:
# Multiply a random tensor of size 2x4 to m
# Elementwise multiplication
m * torch.rand(2, 4)

tensor([[0.3422, 1.5039, 1.3214, 0.8565],
        [3.1104, 5.3571, 3.5393, 5.3944]])

In [52]:
# Divide m by a random tensor of size 2x4 
# Elementwise operation
m / torch.rand(2, 4)

tensor([[ 1.7026,  4.2304,  3.1081,  4.3809],
        [39.9427, 39.4629, 21.6465,  9.3838]])

In [53]:
m.size()

torch.Size([2, 4])

In [54]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [31]:
B, C, H, W = 16, 256, 7, 7 # Band, Channel, Height, Width
A = torch.rand(B, C, H, W)
print(A.shape)
# print(A)
A = A.permute(1, 0, 2, 3)
# print(A)b
print(A.shape)
#
# Assignment to new object is needed because permute does not modify original object.
#

torch.Size([16, 256, 7, 7])
torch.Size([256, 16, 7, 7])


In [32]:
A.permute?

Docstring:
permute(*dims) -> Tensor

See :func:`torch.permute`
Type:      builtin_function_or_method

In [33]:
A.permute??

Docstring:
permute(*dims) -> Tensor

See :func:`torch.permute`
Type:      builtin_function_or_method

In [56]:
m.t().shape

torch.Size([4, 2])

In [57]:
m.t().size()

torch.Size([4, 2])

In [58]:
#Same as
m.T

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [59]:
#Same as
m.transpose(0, 1)

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [60]:
n = torch.tensor([[1, 1, 1, 1],
                  [0, 0, 0, 0]])
n

tensor([[1, 1, 1, 1],
        [0, 0, 0, 0]])

In [61]:
n.shape

torch.Size([2, 4])

In [62]:
m.shape

torch.Size([2, 4])

In [63]:
# Matrix multiplication 
# torch.matmul(torch.tensor, torch.tensor)
# A = (2x4 * 4x2 = 2x2)

A = torch.matmul(m, n.T)
print(A, A.size(), sep=" , ")

tensor([[10,  0],
        [26,  0]]) , torch.Size([2, 2])


In [64]:
# B = (4x2 * 2x4 = 4x4)

B = torch.matmul(m.T, n)
print(B, B.size(), sep=" , ")

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]]) , torch.Size([4, 4])


In [65]:
# Matrix multiplication (4x2 * 2x4 = 4x4)
# torch.tensor.mm(torch.tensor)
BB = m.T
BB.mm(n)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [66]:
# Matrix multiplication 
# using `@` operator
AA = m @ n.T
BBB = m.T @ n
print(AA, BBB, sep="\n")

tensor([[10,  0],
        [26,  0]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])


# Constructor

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [67]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 1.2680e+07],
        [3.0907e-41, 2.5804e+07, 3.0907e-41],
        [1.5282e+29, 4.5820e-41, 1.4013e-45],
        [0.0000e+00, 2.2421e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [68]:
torch.empty?

Docstring:
empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False, memory_format=torch.contiguous_format) -> Tensor

Returns a tensor filled with uninitialized data. The shape of the tensor is
defined by the variable argument :attr:`size`.

.. note::
    If :func:`torch.use_deterministic_algorithms()` and
    :attr:`torch.utils.deterministic.fill_uninitialized_memory` are both set to
    ``True``, the output tensor is initialized to prevent any possible
    nondeterministic behavior from using the data as an input to an operation.
    Floating point and complex tensors are filled with NaN, and integer tensors
    are filled with the maximum value.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desi

In [69]:
x.shape

torch.Size([5, 3])

In [ ]:
#prints dimensional space and sub-dimensions
print(f'point in a {x.numel()} dimensional space')
print(f'organized in {x.dim()} sub-dimensions')

point in a 15 dimensional space
organized in 2 sub-dimensions


Construct a randomly initialized matrix:



In [70]:
x = torch.rand(5, 3)
x

tensor([[0.3082, 0.7799, 0.3652],
        [0.2226, 0.8584, 0.1112],
        [0.2481, 0.0126, 0.9392],
        [0.2136, 0.6597, 0.4378],
        [0.2405, 0.8490, 0.5084]])

In [72]:
torch.rand?

Docstring:
rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optiona

In [ ]:
x.shape

torch.Size([5, 3])

In [ ]:
x.size()

torch.Size([5, 3])

Construct a matrix filled zeros and of dtype long:



Refer to https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype 

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x, x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) torch.int64


In [ ]:
x = torch.zeros(5, 3, dtype=torch.float)
print(x, x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.float32


In [ ]:
x = torch.ones(5, 3)
print(x, x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [ ]:
x = torch.ones(5, 3, dtype=torch.int)
print(x, x.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32) torch.int32


Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x, x.dtype, sep=' , ')

tensor([5.5000, 3.0000]) , torch.float32


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
# y = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
y = x.new_ones(5, 3)                            # new_* methods take in sizes
print(y, y.dtype, sep=' , ')

z = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(z)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) , torch.float32
tensor([-1.3354,  1.0087])


# Operations
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1


In [ ]:
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.6390, 1.4390, 1.1388],
        [1.1094, 1.9890, 1.5862],
        [1.9777, 1.5917, 1.9945],
        [1.4183, 1.0867, 1.4419],
        [1.8494, 1.6028, 1.0023]])


Addition: syntax 2



In [ ]:
print(torch.add(x, y))

tensor([[1.6390, 1.4390, 1.1388],
        [1.1094, 1.9890, 1.5862],
        [1.9777, 1.5917, 1.9945],
        [1.4183, 1.0867, 1.4419],
        [1.8494, 1.6028, 1.0023]])


Addition: providing an output tensor as argument



In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[1.2108e-34, 0.0000e+00, 1.1388e+00],
        [1.1094e+00, 1.9890e+00, 1.5862e+00],
        [1.9777e+00, 1.5917e+00, 1.9945e+00],
        [1.4183e+00, 1.0867e+00, 1.4419e+00],
        [1.8494e+00, 1.6028e+00, 1.0023e+00]])
tensor([[1.6390, 1.4390, 1.1388],
        [1.1094, 1.9890, 1.5862],
        [1.9777, 1.5917, 1.9945],
        [1.4183, 1.0867, 1.4419],
        [1.8494, 1.6028, 1.0023]])


## In-place 

Any operation that mutates a tensor in-place is post-fixed with an `_`. \\
For example: `x.add_(y)`, `x.copy_(y)`, `x.t_()`, `x.zero_()` , `x.random_(n)` will change x.



In [ ]:
# adds x to y
y.add_(x) # y = y + x
print(y)

tensor([[1.6390, 1.4390, 1.1388],
        [1.1094, 1.9890, 1.5862],
        [1.9777, 1.5917, 1.9945],
        [1.4183, 1.0867, 1.4419],
        [1.8494, 1.6028, 1.0023]])


In [ ]:
z = y.clone()
print(z)

tensor([[1.6390, 1.4390, 1.1388],
        [1.1094, 1.9890, 1.5862],
        [1.9777, 1.5917, 1.9945],
        [1.4183, 1.0867, 1.4419],
        [1.8494, 1.6028, 1.0023]])


In [ ]:
y.zero_()
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## Resizing
If you want to resize/reshape tensor, you can use ``torch.view``:

Refer to : 
- [reshape vs. view](https://discuss.pytorch.org/t/difference-between-view-reshape-and-permute/54157)
- [Contiguous tensor](https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays/26999092#26999092)

In short, 
`torch.reshape` may copy the original tensor or not while `torch.view` shares the original one.


In [ ]:
x = torch.rand(4, 4)
print(x.shape, x.numel(), sep=' , ')

y = x.view(16) # y = x.view(x.numel())
print(y.shape, y, sep=' , ')

torch.Size([4, 4]) , 16
torch.Size([16]) , tensor([0.9617, 0.6728, 0.4774, 0.6617, 0.3997, 0.6490, 0.8560, 0.4545, 0.8887,
        0.8831, 0.3430, 0.6140, 0.0721, 0.7838, 0.8405, 0.2161])


In [ ]:
# # x.shape : [batch_size, 64, 7, 7]
# batch_size = 8
# x = torch.rand(batch_size, 100, 7, 7)
# print(f"x shape: {x.shape}")

# x_new = x.view(batch_size, -1) # [batch_size, 100*7*7=4900]
# print(f"x_new shape: {x_new.shape}")
# print(x.view(batch_size, 100*7*7).shape)

x_new shape: torch.Size([8, 4900])
torch.Size([8, 4900])


In [ ]:
z = x.view(-1, 8) # the size -1 is inffered from other dimensions
zz = x.view(-1, 2) # the size -1 is inffered from other dimensions
print(x.shape, z.shape, zz.shape)

torch.Size([4, 4]) torch.Size([2, 8]) torch.Size([8, 2])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2086])
0.20856648683547974


## Broadcasting

In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data).

![대체 텍스트](https://cdn-images-1.medium.com/max/1000/0*lo4N0ZZvMFc903Ab.png)


### General semantics 

Two tensors are “broadcastable” if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be 
    1. equal
    2. one of them is 1 
    3. one of them does not exist.

In [ ]:
# same shapes are always broadcastable (i.e. the above rules always hold)
x=torch.empty(5,7,3)
y=torch.empty(5,7,3)


x=torch.empty((0,))
y=torch.empty(2,2)
# x and y are not broadcastable, because x does not have at least 1 dimension

# can line up trailing dimensions
x=torch.empty(5,3,4,1)
y=torch.empty(  3,1,1) # [3, 1, 1] -> [5, 3, 1, 1]
z = x + y
print(z.shape)
# x and y are broadcastable.
# 1st trailing dimension: both have size 1
# 2nd trailing dimension: y has size 1
# 3rd trailing dimension: x size == y size
# 4th trailing dimension: y dimension doesn't exist

# but:
x=torch.empty(5,2,4,1)
y=torch.empty(  3,1,1)
# x and y are not broadcastable, because in the 3rd trailing dimension 2 != 3

torch.Size([5, 3, 4, 1])


In [ ]:
# Example 1. : one of them does not exist
x = torch.arange(3) #( , 3)
y = torch.tensor(5) #( ,  ) : [] -> [3] : 5 -> [5, 5, 5]
print(x.shape, y.shape)
print(x, y)

print(x + y)

torch.Size([3]) torch.Size([])
tensor([0, 1, 2]) tensor(5)
tensor([5, 6, 7])


In [ ]:
#Example 2. : one of them is 1 + one of them doe not exist
x = torch.arange(3).view(3,1) # (3,1)
y = torch.arange(3)           # ( ,3)
print(x.shape, y.shape)

print(x + y)

torch.Size([3, 1]) torch.Size([3])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])


In [ ]:
#Example 3. : equal + one of them is 1 + one of them doe not exist
x = torch.zeros(2, 2, 3)  # (2, 2, 3)
y = torch.ones(1, 3)      # ( , 1, 3)
print(x.shape, y.shape)

print(x + y, (x+y).shape)

torch.Size([2, 2, 3]) torch.Size([1, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


In [ ]:
# Practical example: learning_rate * gradients of loss
grad_w = torch.rand(8, 3, 3) # e.g., weight's shape: [16, 8, 3, 3]
lr = 0.1 # [0.1] --> [0.1, 0.1, 0.1]
print(grad_w.shape)
print((lr * grad_w).shape)

torch.Size([8, 3, 3])
torch.Size([8, 3, 3])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/torch).




# NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

np.add(a, 1, out=a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.


# CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.


In [ ]:
x = torch.zeros(2,2)
print("x's device : ", x.device)

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")           # a CUDA device object
    y = torch.ones_like(x, device=device)   # directly create a tensor on GPU
    print("y's device : ", y.device)        

    x = x.to(device)                        # or just use strings ``.to("cuda")``
    print("x's device : ", x.device)

    z = x + y
    print(f"z's device: {z.device} & z's dtype: {z.dtype}" )
    
    z.to("cpu", torch.double)        # ``.to`` can also change dtype together!
    print(f"z's device: {z.device} & z's dtype: {z.dtype}" )
    
    z = z.to("cpu", torch.double)
    print(f"z's device: {z.device} & z's dtype: {z.dtype}" )

x's device :  cpu
y's device :  cuda:0
x's device :  cuda:0
z's device: cuda:0 & z's dtype: torch.float32
z's device: cpu & z's dtype: torch.float64


In [ ]:
# w = torch.rand(2, 2)
# print("w's device: ", w.device) # "cpu"

# zz = w + x # RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


# AutoGrad

Autograd: Automatic Differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.





Create a tensor and set ``requires_grad=True`` to track computation with it



In [ ]:
x = torch.ones(2, 2)
print(x.requires_grad)
print(x.device)

False
cpu


In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:

In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.

In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3 # z = 3*(x+2)^2 
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [ ]:
b = (a * a).sum()
print(b.grad_fn)

Gradients
---------
Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``.



In [ ]:
out.backward()

Print gradients $\frac{\partial o}{\partial x}$




In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can also stop autograd from tracking history on Tensors
with ``.requires_grad=True`` either by wrapping the code block in
``with torch.no_grad():``



In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same
content but that does not require gradients:



In [ ]:
print(x.requires_grad)
print(x.grad)

True
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
y = x.detach()
print(y.requires_grad)
print(y.grad)

False
None


In [ ]:
print(x.eq(y).all())

tensor(True)


Efficient inference (testing) with torch.no_grad()
--------

To prevent tracking history (and using memory), you can also wrap the code block in with `torch.no_grad()`

Situation: when **gradient calculation is NOT required** e.g., inference\
Solution: use `torch.no_grad()`, then torch doesn't generate computational graph for back propagation, therefore it is **much faster.**

In [ ]:
with torch.no_grad():
    x = torch.ones(2, 2, requires_grad=True)
    y = x + 2
    z = y * y * 3
    out = z.mean()

In [ ]:
out

tensor(27.)

In [ ]:
# out.backward() ## ERROR!!!!: we used torch.no_grad()!!

# Using pre-defined modules (subset of models) in PyTorch

In [ ]:
import torch.nn as nn

# X's shape: [2, 3]
X = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

print (X)
print (X.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [ ]:
# Linear layer (i.e., fully-conneted layer)
# input dim 3, output dim 1

linear_fn = nn.Linear(3, 1)

In [ ]:
linear_fn  # WX + b

Linear(in_features=3, out_features=1, bias=True)

In [ ]:
linear_fn.weight

Parameter containing:
tensor([[ 0.2533, -0.5754, -0.1774]], requires_grad=True)

In [ ]:
# XW + b
Y = linear_fn(X) # X=[2, 3] (torch.matmul) W[3, 1] -> [2, 1]
print(Y)
print(Y.shape)

tensor([[-1.5613],
        [-3.0599]], grad_fn=<AddmmBackward0>)
torch.Size([2, 1])


In [ ]:
Y = Y.sum()
print(Y)
print(Y.item())

tensor(-4.6212, grad_fn=<SumBackward0>)
-4.621153831481934


You can use other types of `nn.Module` in PyTorch

In [ ]:
nn.Conv2d
nn.RNNCell
nn.LSTMCell
nn.GRUCell
nn.Transformer;

### How can we design a customized model (neural network)?

In [ ]:
class MLP(nn.Module):
    def __init__(self, input_dim, output_dim, hidden_dim):
        super(MLP, self).__init__()
        self.linear_1 = nn.Linear(input_dim, hidden_dim)
        self.linear_2 = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.linear_1(x)
        x = self.relu(x) # Activation function
        x = self.linear_2(x)
        return x

In [ ]:
mlp = MLP(input_dim=3, output_dim=1, hidden_dim=3)

# a = MLP(input_dim=3, output_dim=1, hidden_dim=3)
# a
# b = MLP(input_dim=3, output_dim=1, hidden_dim=3)
# b
# print(a.eq(b).all())

In [ ]:
# X'shape: [2, 3]
print(X.shape)
# z = W2(relu(W1X)) where W1's shape:[2, 3] and W2's shape:[3,1]
z = mlp(X) # [2, 3] x [3, 3] x [3, 1] -> [2, 1]
print(z, z.shape)

torch.Size([2, 3])
tensor([[-0.3207],
        [-1.2725]], grad_fn=<AddmmBackward0>) torch.Size([2, 1])


In [ ]:
# With batch input X2 with a size of [batch_size, 2, 3]
batch_size = 8
X = torch.rand(batch_size, 2, 3)
print(X.shape)

Z = mlp(X)
print(Z.shape)

torch.Size([8, 2, 3])
torch.Size([8, 2, 1])


**What is activation function?**
- They make non-linearity for deep neural networks
- Therefore, deep neural networks can approximate complex functions

In [ ]:
nn.Sigmoid
nn.ReLU
nn.LeakyReLU
nn.Tanh;